name: Run tests for Digy360

on: 
  workflow_dispatch:
    inputs:
      pipelineId:
        description: 'The pipeline ID'  
      requirementId:
        description: 'The requirement ID'  
      tags:
        description: 'Test tags'
      infraUserName:
        description: 'Infrastructure/browserfarm user name'
      infraPassword:
        description: 'Infrastructure/browserfarm password'        
      infraHubUrl:
        description: 'Infrastructure/browserfarm Hub Url'        
      commitId:
        description: 'Commit Id'        
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven to run tests for digycloud
      run: mvn clean install -Ddigy4.commitId="${{github.event.inputs.commitId}}" -Dcucumber.filter.tags="${{github.event.inputs.tags}}" -Ddigy4.pipelineId=${{github.event.inputs.pipelineId}} -Ddigy4.requirementId=${{github.event.inputs.requirementId}} -Ddigy4.tags="${{github.event.inputs.tags}}" -Ddigy4.hubUrl=http://localhost:4443 -Ddigy4.localBrowser=false -Ddigy4.browser=chrome -Ddigy4.testType=API -Ddigy4.framework=cucumber -Ddigy4.buildId=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER} -Ddigy4.projectName=digydashboard -Ddigy4.teamName=Digy360Team -Ddigy4.suiteName=Digy360Suite -Ddigy4.moduleName=Digy360Module -Ddigy4.client_id=b8bf3b196c02d5f4eb8009e7f318a4e5:62221d870d389ee3987dc0b9101f2182 -Ddigy4.client_secret=d9147e9a87c0d906a6ddbbfca1ca7ded:2ddd7b7fa7579821a4ad628a22e9c8d4
