name: Run tests for Digy360

on: 
  workflow_dispatch:
    inputs:
      pipelineId:
        description: 'The pipeline ID'  
      requirementId:
        description: 'The requirement ID'  
      tags:
        description: 'Test tags'
      infraUserName:
        description: 'Infrastructure/browserfarm user name'
      infraPassword:
        description: 'Infrastructure/browserfarm password'        
      infraHubUrl:
        description: 'Infrastructure/browserfarm Hub Url'        
      commitId:
        description: 'Commit Id'        
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven to run tests for digycloud
      run: mvn clean install -Ddigy4.commitId="${{github.event.inputs.commitId}}" -Dcucumber.filter.tags="${{github.event.inputs.tags}}" -Ddigy4.pipelineId=${{github.event.inputs.pipelineId}} -Ddigy4.requirementId=${{github.event.inputs.requirementId}} -Ddigy4.tags="${{github.event.inputs.tags}}" -Ddigy4.hubUrl=http://localhost:4443 -Ddigy4.localBrowser=false -Ddigy4.browser=chrome -Ddigy4.testType=API -Ddigy4.framework=cucumber -Ddigy4.buildId=${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER} -Ddigy4.lob=product -Ddigy4.projectName=digycloud -Ddigy4.teamName=hulk -Ddigy4.suiteName=Digy360Suite -Ddigy4.moduleName=Digy360Module -Ddigy4.client_id=61cfa6e81f4b984a0125e9b3952844c2:50eb874661bd175bda753cf0faaa2197 -Ddigy4.client_secret=19bcf37b9adc32150d35c10b5ffef232:899e345fec1d72fcabc5b1f0572f85fe
